/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application1;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static String name = "xx";

    public static void main(String[] args) {
        int i1 = 2;
        String s1 = "aaabbb123";
        System.out.println(s1);
        System.out.println(new App().getGreeting());
    }
}
