language: java
os: linux
dist: trusty
jdk: oraclejdk8
script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: "acKTqEbgczh7l7oYj3pcM4aX3h9EFKv5EIwwHPiclGYPdnvj6UceAYDdD7PzfdnHP6dYYL+Sgo5kaPUePQxl94vgtkch6pmRhZk8PuxMjBoXEkeLLuFWa4hzDWfnWoGXIZp+fu/AE5OEhecwcJD3En35I/QXpWyM8Nbz62SzmfY3tW1bINpDMl7FtByCfhwoDTWG3ihYVAPX75LO47+n5jg7x43nFEMv79oLImWacpxUX2JIE4/MEY4kATNrlJ77n3kqGP3JgDyoWxMjp2ga5ZkA19yLaykHvRblTUcH5ZKtItCO8ApwPUgy4Z+N9+VVccfECaf2B4npA1XxWUGHYNOKke9+ikxMGwjOcURjlm4Sa6C0vB+sImaRwlpSr3m7nVxkoquok06IDXDDOIXD5W5nHXI2d90OMEMBkJxHZ+/Z/L6csljY8mELi8pIEB7TjvlRW5KYaObcQYL1d3lFkGrOIZRuZzTC9/PuXLbey1Gu0rvRnKf8bi/lEPeNdUwF3AGk+dK0Up0ItuMW+aIZE6jBZivnRzO4zvuYYnya0pkJbfi9RFBYSIU8/3GHzXtboGoBS6cqqZg5TjlfULfDafBTZpmyG/ekqMqitj988VnugKnKudLMMmnfb/xFYiDG83pGYg93Ilg3BwegWckPhESnjGRb9J7BvSem80IiNzQ="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
